---
apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: pull-request-commenter
  labels:
    app.kubernetes.io/version: "0.1"
    upstream-usable: "true"
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: konflux
spec:
  description: |
    This StepAction scans specified directory (workingDir) using [leaktk-scanner CLI](https://github.com/leaktk/scanner)
    and deletes files containing sensitive information (credentials, certificates) that shouldn't be exposed to public.
    Then it pushes the working directory contents to a specified OCI artifact repository tag.
    If the tag exists, it will update the existing content with the content of the working directory.
  image: quay.io/konflux-qe-incubator/konflux-qe-tools:latest
  params:
    - name: test-name
      type: string
      description: The name of the pipeline run being executed.
    - name: oci-container
      type: string
      description: The ORAS container registry URI where the test artifacts are stored.
    - name: pull-request-author
      type: string
      description: The GitHub username of the pull request author.
    - name: pull-request-number
      type: string
      description: The GitHub pull request number to comment on.
    - name: git-repo
      type: string
      description: The GitHub repository name where the pull request is opened.
    - name: git-org
      type: string
      description: The GitHub organization or user owning the repository.
    - name: pipeline-aggregate-status
      type: string
      description: The aggregate status of the pipeline run (Succeeded, Failed, Completed, None).
      default: None
    - name: git-revision
      type: string
      description: The Git commit revision associated with the pull request.
    - name: junit-report-name
      type: string
      default: junit.xml
      description: The name of the JUnit file to be used for test results analysis
    - name: e2e-log-name
      type: string
      default: e2e-tests.log
      description: The name of the log file from E2E tests run to be used for test results analysis
    - name: cluster-provision-log-name
      type: string
      default: cluster-provision.log
      description: The name of the log file from cluster provisioning to be used for test results analysis
    - name: enable-test-results-analysis
      type: string
      default: "false"
      description: Add "true" if you want to enable experimental test analysis step
    - name: artifact-browser-url
      type: string
      default: ""
      description: Provides the URL to the artifact browser deployment.
  env:
    - name: BUILD_CONSOLE_URL
      valueFrom:
        fieldRef:
          fieldPath: metadata.annotations['pac.test.appstudio.openshift.io/log-url']
    - name: WORKSPACE_BASIC_AUTH_DIRECTORY_BOUND
      value: $(workspaces.basic-auth.bound)
    - name: WORKSPACE_BASIC_AUTH_DIRECTORY_PATH
      value: $(workspaces.basic-auth.path)
    - name: TEST_NAME
      value: "$(params.test-name)"
    - name: PR_AUTHOR
      value: "$(params.pull-request-author)"
    - name: OCI_STORAGE_CONTAINER
      value: "$(params.oci-container)"
    - name: GIT_ORG
      value: "$(params.git-org)"
    - name: GIT_REPO
      value: "$(params.git-repo)"
    - name: PR_NUMBER
      value: "$(params.pull-request-number)"
    - name: PIPELINE_RUN_AGGREGATE_STATUS
      value: "$(params.pipeline-aggregate-status)"
    - name: ARTIFACT_BROWSER_URL
      value: "$(params.artifact-browser-url)"
  workingDir: /workspace
  script: |
    #!/bin/sh

    PIPELINE_STATUS=$(kubectl get pipelinerun ${TEST_NAME} -o jsonpath='{.status.conditions[0].reason}')

    if [ "${PIPELINE_STATUS}" = "CancelledRunningFinally" ]; then
      echo "PipelineRun was cancelled. Skipping sending a comment to the PR."
      exit 0
    fi


    if [ "${WORKSPACE_BASIC_AUTH_DIRECTORY_BOUND}" = "true" ]; then
      echo "configuring gh cli"
      ls -la "${WORKSPACE_BASIC_AUTH_DIRECTORY_PATH}"
      GITHUB_TOKEN=$(cat "${WORKSPACE_BASIC_AUTH_DIRECTORY_PATH}/git-provider-token")
      echo "taking github token from Konflux bot"
    fi
    if [ -z "$GITHUB_TOKEN" ]; then
        echo "Error: GITHUB_TOKEN env is not set."
        exit 1
    fi
    # Get the authenticated user's login
    USER_LOGIN=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
        "https://api.github.com/user" | jq -r '.login')

    if [ -z "$USER_LOGIN" ]; then
        echo "[ERROR] Unable to retrieve user login."
        exit 1
    fi

    # Get all comments on the pull request
    COMMENTS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
        "https://api.github.com/repos/$GIT_ORG/$GIT_REPO/issues/$PR_NUMBER/comments")

    # Find and delete any existing comments by the authenticated user
    COMMENT_IDS=$(echo "$COMMENTS" | jq -r --arg USER_LOGIN "$USER_LOGIN" '.[] | select(.user.login == $USER_LOGIN) | .id')
    for COMMENT_ID in $COMMENT_IDS; do
        DELETE_RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -X DELETE \
            "https://api.github.com/repos/$GIT_ORG/$GIT_REPO/issues/comments/$COMMENT_ID")

        if [ -z "$DELETE_RESPONSE" ]; then
            echo "[INFO] Existing comment with ID $COMMENT_ID by $USER_LOGIN deleted successfully."
        else
            echo "[ERROR] Failed to delete comment with ID $COMMENT_ID. Response: $DELETE_RESPONSE"
        fi
    done

    # If the pipeline succeeded, do not post a new comment and exit
    # if [[ "$PIPELINE_RUN_AGGREGATE_STATUS" == "Succeeded" ]]; then
    #     echo "[INFO]: Pipeline finished successfully. No new comment will be posted."
    #     exit 0
    # fi

    # Construct build/integration console url based on whether we are running this task inside build-definitions build pipeline or konflux integration test pipeline
    if [ -z "${BUILD_CONSOLE_URL}" ]; then
      echo "[INFO] Task is running inside build-definitions build pipeline"
      export BUILD_CONSOLE_URL="$(oc whoami --show-console)/k8s/ns/konflux-ci/tekton.dev~v1~PipelineRun/${TEST_NAME}"
      export INTEGRATION_TEST_CONSOLE_URL="${BUILD_CONSOLE_URL}/logs?taskName=e2e-tests"
    else
      export INTEGRATION_TEST_CONSOLE_URL="${BUILD_CONSOLE_URL%/*}/${TEST_NAME}"
    fi

    # Store the content of the test results analysis (from a previous step) in a variable
    TEST_RESULTS_ANALYSIS=$(cat analysis.md || echo "\<not enabled\>")

    # Generate artifact browser link if URL is provided
    # ARTIFACT_BROWSER_URL=$(echo "\<not enabled\>")
    if [ -n "${ARTIFACT_BROWSER_URL}" ]; then
        # Use the provided artifact browser URL
        export ARTIFACT_BROWSER_BASE_URL="${ARTIFACT_BROWSER_URL}"
        # Extract repository name from OCI container reference
        REPO_NAME=$(echo "$OCI_STORAGE_CONTAINER" | sed 's|.*/||' | sed 's|:.*||')
        ARTIFACT_BROWSER_URL="[View in Artifact Browser](${ARTIFACT_BROWSER_BASE_URL}/${REPO_NAME}/${TEST_NAME}/)"
    fi

    PR_COMMENT=$(cat <<EOF
    @${PR_AUTHOR}: The following test has ${PIPELINE_RUN_AGGREGATE_STATUS}:
    ### OCI Artifact Browser URL
    ${ARTIFACT_BROWSER_URL}
    ### Inspecting Test Artifacts Manually
    To inspect your test artifacts manually, follow these steps:
    1. Install **ORAS** (see the [ORAS installation guide](https://oras.land/docs/installation)).
    2. Download artifacts with the following commands:

    \`\`\`sh
    mkdir -p oras-artifacts
    cd oras-artifacts
    oras pull $OCI_STORAGE_CONTAINER
    \`\`\`
    EOF
    )
    # Combine body components into the final JSON body
    REQUEST_DATA=$(jq -n --arg body "${PR_COMMENT}" '{body: $body}')

    # Post the comment to GitHub
    RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
        -H "Content-Type: application/json" \
        -X POST \
        -d "$REQUEST_DATA" \
        "https://api.github.com/repos/$GIT_ORG/$GIT_REPO/issues/$PR_NUMBER/comments")

    # Check if the comment was posted successfully
    if echo "$RESPONSE" | grep -q '"id"'; then
        echo "[INFO] Comment posted successfully."
    else
        echo "[ERROR] Failed to post comment. Response: $RESPONSE"
        echo "https://api.github.com/repos/$GIT_ORG/$GIT_REPO/issues/$PR_NUMBER/comments"
    fi
