---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: prefetch-dependencies-oci-ta
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: image-build, konflux
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  description: |-
    Task that prefetches all the deployment manifests for all the operands of the ODH/RHODS operator. 
    It is a tekton equivalent of the existing operator-processor github workflow.
    It ensures to follow the oci-ta standards to gel well in the Konflux infrastructure framework.
  params:
    - name: SOURCE_ARTIFACT
      description: The Trusted Artifact URI pointing to the artifact with
        the application source code.
      type: string
    - name: caTrustConfigMapKey
      description: The name of the key in the ConfigMap that contains the
        CA bundle data.
      type: string
      default: ca-bundle.crt
    - name: caTrustConfigMapName
      description: The name of the ConfigMap to read CA bundle data from.
      type: string
      default: trusted-ca
    - name: ociArtifactExpiresAfter
      description: Expiration date for the trusted artifacts created in the
        OCI repository. An empty string means the artifacts do not expire.
      type: string
      default: "1d"
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored.
      type: string
    - name: utilsRepoUrl
      description: Git URL of the RHOAI-Konflux-Automation repo
      type: string
      default: "https://github.com/rhoai-rhtap/RHOAI-Konflux-Automation.git"
    - name: utilsRepoBranch
      description: Git branch of the RHOAI-Konflux-Automation repo
      type: string
      default: "main"
    - name: buildConfigRepoUrl
      description: Git URL of the Build-Config repo
      type: string
      default: "https://github.com/opendatahub-io/ODH-Build-Config.git"
    - name: buildConfigRepoBranch
      description: Git branch of the Build-Config repo
      type: string
      default: "main"
    - name: buildVersionTag
      description: Image tag of operand images to be sought by operator-processor
      type: string
      default: "latest"
  results:
    - name: CACHI2_ARTIFACT
      description: The Trusted Artifact URI pointing to the artifact with
        the prefetched dependencies.
      type: string
    - name: SOURCE_ARTIFACT
      description: The Trusted Artifact URI pointing to the artifact with
        the application source code.
      type: string
  volumes:
    - name: config
      emptyDir: {}
    - name: trusted-ca
      configMap:
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        name: $(params.caTrustConfigMapName)
        optional: true
    - name: workdir
      emptyDir: {}
  workspaces:
    - name: git-basic-auth
      description: |
        A Workspace containing a .gitconfig and .git-credentials file or username and password.
        These will be copied to the user's home before any cachi2 commands are run. Any
        other files in this Workspace are ignored. It is strongly recommended
        to bind a Secret to this Workspace over other volume types.
      optional: true
    - name: netrc
      description: |
        Workspace containing a .netrc file. Cachi2 will use the credentials in this file when
        performing http(s) requests.
      optional: true
  stepTemplate:
    env:
      - name: UTILS_REPO_URL
        value: $(params.utilsRepoUrl)
      - name: UTILS_REPO_BRANCH
        value: $(params.utilsRepoBranch)
      - name: BUILD_CONFIG_REPO_URL
        value: $(params.buildConfigRepoUrl)
      - name: BUILD_CONFIG_REPO_BRANCH
        value: $(params.buildConfigRepoBranch)
      - name: RHOAI_QUAY_API_TOKEN
        value: ""
      - name: OPENDATAHUB_QUAY_API_TOKEN
        value: ""
      - name: BUILD_VERSION_TAG
        value: $(params.buildVersionTag)
    volumeMounts:
      - mountPath: /mnt/config
        name: config
      - mountPath: /var/workdir
        name: workdir
  steps:
    - name: use-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:81c4864dae6bb11595f657be887e205262e70086a05ed16ada827fd6391926ac
      args:
        - use
        - $(params.SOURCE_ARTIFACT)=/var/workdir/source
    - name: prefetch-manifests
      image: quay.io/rhoai/rhoai-task-toolset:latest
      volumeMounts:
        - mountPath: /mnt/trusted-ca
          name: trusted-ca
          readOnly: true
      env:
        - name: WORKSPACE_GIT_AUTH_BOUND
          value: $(workspaces.git-basic-auth.bound)
        - name: WORKSPACE_GIT_AUTH_PATH
          value: $(workspaces.git-basic-auth.path)
        - name: WORKSPACE_NETRC_BOUND
          value: $(workspaces.netrc.bound)
        - name: WORKSPACE_NETRC_PATH
          value: $(workspaces.netrc.path)
      workingDir: /var/workdir
      script: |
        # Install dependencies
        os="$(uname -s | tr '[:upper:]' '[:lower:]')"
        arch="$(uname -m | sed 's/x86_64/amd64/')"
        yq_version="v4.44.3"
        yq_filename="yq-$yq_version"
        echo "-> Downloading yq" >&2
        curl -sSfLo "$yq_filename" "https://github.com/mikefarah/yq/releases/download/$yq_version/yq_${os}_${arch}"
        chmod +x $yq_filename
        ln -s $yq_filename yq
        cp $yq_filename /usr/local/bin/yq
        
        mkdir -p playpen
        git clone ${UTILS_REPO_URL} --branch ${UTILS_REPO_BRANCH} utils
        ls utils
        
        git clone ${BUILD_CONFIG_REPO_URL} --branch ${BUILD_CONFIG_REPO_BRANCH} RBC
        ls RBC
        
        pip install --default-timeout=100 -r utils/utils/operator-processor/requirements.txt
        
          ODH_OPERATOR_COMPONENT_NAME=odh-ci-operator
          
          PATCH_YAML_PATH=RBC/bundle/bundle-patch.yaml
          OPERANDS_MAP_PATH=source/build/operands-map.yaml
          MANIFEST_CONFIG_PATH=source/build/manifests-config.yaml
          PUSH_PIPELINE_PATH=source/.tekton/${ODH_OPERATOR_COMPONENT_NAME}-push.yaml
        
          python3 utils/utils/operator-processor/operator-processor.py  -op process-operator-yamls --patch-yaml-path ${PATCH_YAML_PATH} --operands-map-path ${OPERANDS_MAP_PATH} --manifest-config-path ${MANIFEST_CONFIG_PATH} --rhoai-version ${BUILD_VERSION_TAG} --push-pipeline-yaml-path ${PUSH_PIPELINE_PATH} --push-pipeline-operation enable
          
          echo "----- OPERANDS_MAP ------"
          cat $OPERANDS_MAP_PATH
          echo "----- MANIFEST_CONFIG ------"
          cat $MANIFEST_CONFIG_PATH
          echo "current dir = $(pwd)"
        
        # git clone https://github.com/red-hat-data-services/rhods-operator.git --branch rhoai-3.2 operator
        # mv -t ./ operator/prefetched-manifests

#    - name: prefetch-dependencies
#      image: quay.io/redhat-appstudio/cachi2:0.13.0@sha256:eb34cfe3fea20997eebd8164dc93eedb2fd7a60dc1fb4afcc1b1ff43df9d6667
#      volumeMounts:
#        - mountPath: /mnt/trusted-ca
#          name: trusted-ca
#          readOnly: true
#      env:
#        - name: INPUT
#          value: $(params.input)
#        - name: DEV_PACKAGE_MANAGERS
#          value: $(params.dev-package-managers)
#        - name: LOG_LEVEL
#          value: $(params.log-level)
#        - name: WORKSPACE_GIT_AUTH_BOUND
#          value: $(workspaces.git-basic-auth.bound)
#        - name: WORKSPACE_GIT_AUTH_PATH
#          value: $(workspaces.git-basic-auth.path)
#        - name: WORKSPACE_NETRC_BOUND
#          value: $(workspaces.netrc.bound)
#        - name: WORKSPACE_NETRC_PATH
#          value: $(workspaces.netrc.path)
#      script: |
#        if [ -z "${INPUT}" ]; then
#          # Confirm input was provided though it's likely the whole task would be skipped if it wasn't
#          echo "No prefetch will be performed because no input was provided for cachi2 fetch-deps"
#          exit 0
#        fi
#
#        if [ -f /mnt/config/config.yaml ]; then
#          config_flag=--config-file=/mnt/config/config.yaml
#        else
#          config_flag=""
#        fi
#
#        if [ "$DEV_PACKAGE_MANAGERS" = "true" ]; then
#          dev_pacman_flag=--dev-package-managers
#        else
#          dev_pacman_flag=""
#        fi
#
#        # Copied from https://github.com/konflux-ci/build-definitions/blob/main/task/git-clone/0.1/git-clone.yaml
#        if [ "${WORKSPACE_GIT_AUTH_BOUND}" = "true" ]; then
#          if [ -f "${WORKSPACE_GIT_AUTH_PATH}/.git-credentials" ] && [ -f "${WORKSPACE_GIT_AUTH_PATH}/.gitconfig" ]; then
#            cp "${WORKSPACE_GIT_AUTH_PATH}/.git-credentials" "${HOME}/.git-credentials"
#            cp "${WORKSPACE_GIT_AUTH_PATH}/.gitconfig" "${HOME}/.gitconfig"
#          # Compatibility with kubernetes.io/basic-auth secrets
#          elif [ -f "${WORKSPACE_GIT_AUTH_PATH}/username" ] && [ -f "${WORKSPACE_GIT_AUTH_PATH}/password" ]; then
#            HOSTNAME=$(cd "/var/workdir/source" && git remote get-url origin | awk -F/ '{print $3}')
#            echo "https://$(cat ${WORKSPACE_GIT_AUTH_PATH}/username):$(cat ${WORKSPACE_GIT_AUTH_PATH}/password)@$HOSTNAME" >"${HOME}/.git-credentials"
#            echo -e "[credential \"https://$HOSTNAME\"]\n  helper = store" >"${HOME}/.gitconfig"
#          else
#            echo "Unknown git-basic-auth workspace format"
#            exit 1
#          fi
#          chmod 400 "${HOME}/.git-credentials"
#          chmod 400 "${HOME}/.gitconfig"
#        fi
#
#        if [ "${WORKSPACE_NETRC_BOUND}" = "true" ]; then
#          cp "${WORKSPACE_NETRC_PATH}/.netrc" "${HOME}/.netrc"
#        fi
#
#        ca_bundle=/mnt/trusted-ca/ca-bundle.crt
#        if [ -f "$ca_bundle" ]; then
#          echo "INFO: Using mounted CA bundle: $ca_bundle"
#          cp -vf $ca_bundle /etc/pki/ca-trust/source/anchors
#          update-ca-trust
#        fi
#
#        cachi2 --log-level="$LOG_LEVEL" $config_flag fetch-deps \
#          $dev_pacman_flag \
#          --source=/var/workdir/source \
#          --output=/var/workdir/cachi2/output \
#          "${INPUT}"
#
#        cachi2 --log-level="$LOG_LEVEL" generate-env /var/workdir/cachi2/output \
#          --format env \
#          --for-output-dir=/cachi2/output \
#          --output /var/workdir/cachi2/cachi2.env
#
#        cachi2 --log-level="$LOG_LEVEL" inject-files /var/workdir/cachi2/output \
#          --for-output-dir=/cachi2/output
    - name: create-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:81c4864dae6bb11595f657be887e205262e70086a05ed16ada827fd6391926ac
      args:
        - create
        - --store
        - $(params.ociStorage)
        - $(results.SOURCE_ARTIFACT.path)=/var/workdir/source
        - $(results.CACHI2_ARTIFACT.path)=/var/workdir/prefetched-manifests
      env:
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.ociArtifactExpiresAfter)
