apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: trigger-bundle-build
spec:
  workspaces:
    - name: basic-auth
      optional: true
  params:
    - description: bundle repo name
      name: bundle-repo-name
      type: string
      default: "opendatahub-io/ODH-Build-Config"
    - description: bundle repo git branch
      name: bundle-branch-name
      type: string
      default: "main"
    - description: bundle-processor workflow file name
      name: bundle-processor-workflow-file-name
      type: string
      default: "process-operator-bundle.yaml"
  steps:
  - image: quay.io/konflux-ci/konflux-test:stable
    name: trigger-bundle-build
    env:
    - name: BUNDLE_REPO_NAME
      value: "$(params.bundle-repo-name)"
    - name: BUNDLE_BRANCH_NAME
      value: "$(params.bundle-branch-name)"
    - name: BUNDLE_PROCESSOR_WORKFLOW_ID
      value: "$(params.bundle-processor-workflow-file-name)"
    - name: WORKSPACE_BASIC_AUTH_DIRECTORY_BOUND
      value: $(workspaces.basic-auth.bound)
    - name: WORKSPACE_BASIC_AUTH_DIRECTORY_PATH
      value: $(workspaces.basic-auth.path)
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: odh-github-secret
          key: bundle-ci-token
    script: |
      #!/bin/bash
      set -e
      echo "----- DEBUG INFORMATION -----"
      echo "BUNDLE_REPO_NAME: ${BUNDLE_REPO_NAME}"
      echo "BUNDLE_BRANCH_NAME: ${BUNDLE_BRANCH_NAME}"
      echo "BUNDLE_PROCESSOR_WORKFLOW_ID: ${BUNDLE_PROCESSOR_WORKFLOW_ID}"
      INPUTS=""
      
      if [ "${WORKSPACE_BASIC_AUTH_DIRECTORY_BOUND}" = "true" ]; then
        echo "configuring gh cli"
        ls -la "${WORKSPACE_BASIC_AUTH_DIRECTORY_PATH}"
        # GITHUB_TOKEN=$(cat "${WORKSPACE_BASIC_AUTH_DIRECTORY_PATH}/git-provider-token")
      fi
      if [[ -n "$INPUTS" ]]; then
        PAYLOAD=$(jq -n --arg ref "$BUNDLE_BRANCH_NAME" --argjson inputs "$INPUTS" '{ref: $ref, inputs: $inputs}')
      else
        PAYLOAD=$(jq -n --arg ref "$BUNDLE_BRANCH_NAME" '{ref: $ref}')
      fi
      API_URL="https://api.github.com/repos/${BUNDLE_REPO_NAME}/actions/workflows/${BUNDLE_PROCESSOR_WORKFLOW_ID}/dispatches"
      
      echo "Triggering workflow '${BUNDLE_PROCESSOR_WORKFLOW_ID}' on ${BUNDLE_REPO_NAME} (ref: ${BUNDLE_BRANCH_NAME})..."
      
      TEMP_FILE=$(mktemp)
      
      HTTP_CODE=$(curl -s -o "$TEMP_FILE" -w "%{http_code}" \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${GITHUB_TOKEN}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        "$API_URL" \
        -d "$PAYLOAD")
      
      if [[ "$HTTP_CODE" == "204" ]]; then
        echo "Workflow dispatched successfully."
      else
        echo "Failed to dispatch workflow. HTTP status: ${HTTP_CODE}"
        cat "$TEMP_FILE"
        exit 1
      fi