apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: inject-sealights-into-bundle-oci-ta
spec:
  params:
  - name: SOURCE_ARTIFACT
    description: The Trusted Artifact URI pointing to the artifact with
      the application source code.
    type: string 
  - name: oci-storage
    description: The OCI repository where the Trusted Artifacts are stored.
    type: string
  - name: sealights-integrated-repos
    description: names of rhoai quay repos that are integrated with sealights
  results:
  - description: Modified source code
    name: SOURCE_ARTIFACT
  steps: 
  - name: use-trusted-artifact
    image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:edd8e3affc389320b15b9de8a5aedbf7b0463211b77c981563a2cfa20076b0c0
    args:
    - use
    - $(params.SOURCE_ARTIFACT)=/var/workdir/source
  - image: quay.io/konflux-ci/tekton-integration-catalog/utils:latest
    name: inject-sealights
    env:
    - name: SEALIGHTS_INTEGRATED_REPOS
      value: $(params.sealights-integrated-repos[*])
    script: |
      set -eo pipefail
      cd /var/workdir/source

      function get_sealights_image {
        REAL_QUAY_URI=$1
        SEALIGHTS_BUILD_STEP=$2

        ### Get the attestation info from the actual build URI
        cosign download attestation $REAL_QUAY_URI > attestation.json

        SEALIGHTS_BUILD_RESULTS=$(jq '.payload|@base64d|fromjson' attestation.json \
          | jq -r --arg N "$SEALIGHTS_BUILD_STEP" '.predicate.buildConfig.tasks[] | select(.name == $N)| .results')

        ### Find the sealights build URI from the attestation

        # this has the form 'sha256:<digest>'
        SEALIGHTS_IMAGE_DIGEST=$(echo $SEALIGHTS_BUILD_RESULTS | jq -r '.[] | select(.name == "IMAGE_DIGEST") | .value' | head -n 1)

        # using sed to remove the tag, leaving just the repo url
        SEALIGHTS_IMAGE_REPO=$(echo $SEALIGHTS_BUILD_RESULTS | jq -r '.[] | select(.name == "IMAGE_URL") | .value' | sed 's/:.*//' | head -n 1)

        echo "${SEALIGHTS_IMAGE_REPO}@${SEALIGHTS_IMAGE_DIGEST}"
        rm attestation.json
        rm /tmp/auth/config.json
      }

      # SEALIGHTS_INTEGRATED_REPOS=odh-dashboard-rhel9 

      for SEALIGHTS_INTEGRATED_REPO in $SEALIGHTS_INTEGRATED_REPOS; do
        echo "Processing $SEALIGHTS_INTEGRATED_REPO"

        ### Find the actual build uri
        REAL_URI=$(grep "registry\.redhat\.io/rhoai" manifests/rhods-operator.clusterserviceversion.yaml | \
          grep -m 1 "$SEALIGHTS_INTEGRATED_REPO" | grep -E -o 'registry\.redhat\.io/rhoai/.*@sha256:.{64}')
        REAL_QUAY_URI=$(echo "$REAL_URI" | sed 's/registry\.redhat\.io/quay.io/')
        echo "Found $REAL_URI"
        echo " -> converting to $REAL_QUAY_URI"

        SEALIGHTS_QUAY_URI=$(get_sealights_image "$REAL_QUAY_URI" "build-sealights-image-index" | tail -n 1)
        SEALIGHTS_URI=$(echo "$SEALIGHTS_QUAY_URI" | sed 's/quay\.io/registry.redhat.io/')
        echo "Found sealights URI $SEALIGHTS_QUAY_URI"
        echo " -> converting to $SEALIGHTS_URI"

        # replace the real URI with the sealights ones
        echo "Replacing all instances of $REAL_URI"
        echo " with $SEALIGHTS_URI"
        sed -i "s|$REAL_URI|$SEALIGHTS_URI|g" manifests/rhods-operator.clusterserviceversion.yaml
      done

      echo "finished processing"
  - name: create-trusted-artifact
    image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:edd8e3affc389320b15b9de8a5aedbf7b0463211b77c981563a2cfa20076b0c0
    args:
    - create
    - --store
    - $(params.oci-storage)
    - $(results.SOURCE_ARTIFACT.path)=/var/workdir/source
