apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/red-hat-data-services/rhoai-konflux-tasks?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    # TODO: include rhoai-x.y as a branch target 
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" 
      && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: automation
    appstudio.openshift.io/component: rhoai-konflux-tasks
    pipelines.appstudio.openshift.io/type: build
  name: rhoai-konflux-tasks-on-push
  namespace: rhoai-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: target-branch
    value: '{{target_branch}}'
  - name: additional-tags
    value: 
    - '{{target_branch}}-{{revision}}'
  - name: additional-labels
    value: 
    - version=v2.Y.Z
    - io.openshift.tags=ADDITIONAL_TAG_HERE
  - name: output-image
    value: quay.io/redhat-user-workloads/rhoai-tenant/rhoai-konflux-tasks:{{revision}}
  - name: dockerfile
    value: ./test-build/Dockerfile.konflux
  - name: path-context
    value: .
  # - name: prefetch-input
  #   value: |
  #   [{"type": "gomod"}, {"type": "rpm"}]
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/red-hat-data-services/rhoai-konflux-tasks.git
    - name: revision
      value: '{{ revision }}'
    - name: pathInRepo
      value: pipelines/container-build.yaml
  taskRunTemplate: {}
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
