apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: git-clone
  labels:
    upstream-usable: "true"
spec:
  description: |
    This StepAction scans specified directory (workingDir) using [leaktk-scanner CLI](https://github.com/leaktk/scanner)
    and deletes files containing sensitive information (credentials, certificates) that shouldn't be exposed to public.
    Then it pushes the working directory contents to a specified git repo.
  image: quay.io/konflux-qe-incubator/konflux-qe-tools:latest
  params:
    - name: repo-path
      type: string
    - name: repo-branch
      type: string
    - name: sparse-file-path
      type: string
      default: ""
    - name: dest-path
      type: string
      default: ""
    - name: artifacts-dir-path
      type: string
      default: ""
    - name: always-pass
      type: string
      default: "false"
  workingDir: /workspace/odh-ci-artifacts
  env:
    - name: REPO_PATH
      value: "$(params.repo-path)"
    - name: REPO_BRANCH
      value: "$(params.repo-branch)"
    - name: SPARSE_FILE_PATH
      value: "$(params.sparse-file-path)"
    - name: DEST_PATH
      value: "$(params.dest-path)"
    - name: ARTIFACTS_DIR_PATH
      value: "$(params.artifacts-dir-path)"
    - name: ALWAYS_PASS
      value: "$(params.always-pass)"
    - name: WORKSPACE_BASIC_AUTH_DIRECTORY_BOUND
      value: $(workspaces.basic-auth.bound)
    - name: WORKSPACE_BASIC_AUTH_DIRECTORY_PATH
      value: $(workspaces.basic-auth.path)
  script: |
    #!/bin/bash
    set -e

    echo "REPO_PATH: $REPO_PATH"
    echo "REPO_BRANCH: $REPO_BRANCH"
    echo "SPARSE_FILE_PATH: $SPARSE_FILE_PATH"
    echo "DEST_PATH: $DEST_PATH"
    echo "ALWAYS_PASS: $ALWAYS_PASS"
    echo "ARTIFACTS_DIR_PATH: $ARTIFACTS_DIR_PATH"

    main() {
          if [ "${WORKSPACE_BASIC_AUTH_DIRECTORY_BOUND}" = "true" ]; then
            echo "configuring gh token"
            GITHUB_TOKEN=$(cat "${WORKSPACE_BASIC_AUTH_DIRECTORY_PATH}/git-provider-token")
            echo "taking github token from Konflux bot"
          fi
          if [ -z "$GITHUB_TOKEN" ]; then
              echo "Error: GITHUB_TOKEN env is not set."
              exit 1
          fi
    
          mkdir -p ${DEST_PATH}
          cd ${DEST_PATH}
          git config --global init.defaultBranch ${REPO_BRANCH}
          git config --global user.name "OpenShift-AI-DevOps"
          git config --global user.email "openshift-ai-devops@redhat.com"
          git init
          git config --global --add safe.directory ${DEST_PATH}
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO_PATH}.git"
          if [[ -n "${SPARSE_FILE_PATH}" ]]; then
              git config core.sparseCheckout true
              git config core.sparseCheckoutCone false
              echo "${SPARSE_FILE_PATH}" >> .git/info/sparse-checkout
          fi
          git fetch --depth=1 origin ${REPO_BRANCH}
          git checkout ${REPO_BRANCH}
    
          if [[ -e "${ARTIFACTS_DIR_PATH}" ]]; then
            cd ${ARTIFACTS_DIR_PATH}
            for f in *.tar.gz; do
              tar -xzf "$f"
            done
            rm -rf *.tar.gz
          fi

    }

    if [ "$ALWAYS_PASS" == "true" ]; then
      main || true
    else
      main
    fi
