apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: secure-git-push
  labels:
    upstream-usable: "true"
spec:
  description: |
    This StepAction scans specified directory (workingDir) using [leaktk-scanner CLI](https://github.com/leaktk/scanner)
    and deletes files containing sensitive information (credentials, certificates) that shouldn't be exposed to public.
    Then it pushes the working directory contents to a specified git repo.
  image: quay.io/konflux-qe-incubator/konflux-qe-tools:latest
  params:
    - name: artifact-dir
      type: string
    - name: repo-path
      type: string
    - name: repo-branch
      type: string
    - name: sparse-file-path
      type: string
      default: ""
    - name: source-path
      type: string
    - name: dest-path
      type: string
    - name: always-pass
      type: string
      default: "false"
  volumeMounts:
  - name: $(params.credentials-volume-name)
    mountPath: /home/tool-box/.docker/config.json
    subPath: oci-storage-dockerconfigjson
  workingDir: $(params.workdir-path)
  env:
    - name: REPO_PATH
      value: "$(params.repo-path)"
    - name: REPO_BRANCH
      value: "$(params.repo-branch)"
    - name: SPARSE_FILE_PATH
      value: "$(params.sparse-file-path)"
    - name: SOURCE_PATH
      value: "$(params.source-path)"
    - name: DEST_PATH
      value: "$(params.dest-path)"
    - name: ALWAYS_PASS
      value: "$(params.always-pass)"
    - name: GIT_DIR
      value: /workspace/odh-ci-artifacts
  script: |
    #!/bin/bash
    set -e

    echo "GIT_DIR: $GIT_DIR"
    echo "REPO_PATH: $REPO_PATH"
    echo "REPO_BRANCH: $REPO_BRANCH"
    echo "SPARSE_FILE_PATH: $SPARSE_FILE_PATH"
    echo "SOURCE_PATH: $SOURCE_PATH"
    echo "DEST_PATH: $DEST_PATH"
    echo "ALWAYS_PASS: $ALWAYS_PASS"

    main() {

          mkdir -p ${GIT_DIR}
          cd ${GIT_DIR}
          git config --global init.defaultBranch ${REPO_BRANCH}
          git config --global user.name "OpenShift-AI-DevOps"
          git config --global user.email "openshift-ai-devops@redhat.com"
          git init
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO_PATH}.git"
          if [[ -n "${SPARSE_FILE_PATH}" ]]; then
              git config core.sparseCheckout true
              git config core.sparseCheckoutCone false
              echo "${SPARSE_FILE_PATH}" >> .git/info/sparse-checkout
          fi
          git fetch --depth=1 origin ${REPO_BRANCH}
          git checkout ${REPO_BRANCH}
    
          mkdir -p ${GIT_DIR}/${DEST_PATH}
          cp -r ${SOURCE_PATH} ${GIT_DIR}/${DEST_PATH}
          cd ${GIT_DIR}/${DEST_PATH}
    
          # Scan the working directory using leaktk-scanner and remove problematic files
          log_filename="leaktk-scan-$(date +%s).log"
          leaktk-scanner scan --kind Files --resource . 2>> $log_filename | leaktk-remove-files . &>> $log_filename
    
          #push the changes to remote
          git add --sparse ${GIT_DIR}/${DEST_PATH}
          git commit -m "Updating CI Artifacts in {DEST_PATH}"
          git push

    }

    if [ "$ALWAYS_PASS" == "true" ]; then
      main || true
    else
      main
    fi
